name: Deploy Leading Edge (master)

on:
    push:
        branches: [master]
env:
    API_TOKEN_GITHUB: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
    GIT_USER_EMAIL: ${{ secrets.GH_ACTIONS_GIT_USER_EMAIL }}
    GIT_USER_NAME: ${{ secrets.GH_ACTIONS_GIT_USER_NAME }}
    FORCE_COLOR: true
jobs:
    deploy-domains-and-packages:
        runs-on: ubuntu-latest
        name: Deploy domains and packages
        steps:
            - name: Setup SSH
              uses: MrSquaare/ssh-setup-action@v1
              with:
                  host: github.com
                  private-key: ${{ secrets.GH_ACTIONS_SSH_PRIVATE_KEY }}

            - name: Checkout the commit
              uses: actions/checkout@v2

            # TODO replace this when setup-node action supports LTS alias
            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            # Install all dependencies at root
            - name: Install dependencies
              # install deps only if lockfile has changed
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            # Build the core domains along with all the packages
            # because all packages will goto core
            - name: Build core domains and all their packages
              run: yarn build:core

            # Deploy the built assets to core repo's assets/dist
            - name: Deploy to event-espresso-core
              run: source tools/deploy.sh "event-espresso-core"

            # Build REM domain without packages
            # because core will load/register the packages
            - name: Build REM with its packages
              run: yarn build:rem

            # Deploy the built assets to REM assets/dist
            - name: Deploy to REM
              run: source tools/deploy.sh "eea-recurring-events-manager"

            # Build WP User domain without packages
            - name: Build wpUser
              run: yarn build:wpUser

            # Deploy the built assets to WP User assets/dist
            - name: Deploy to WP User
              run: source tools/deploy.sh "eea-wpuser-integration"

            # Build EventSmart domain without packages
            - name: Build ES
              run: yarn build:es

            # Deploy the built assets to ES tester plugin assets
            - name: Deploy to ES website repo
              run: source tools/deploy.sh "eventsmart.com-website" "dev" "plugins/es-barista-tester/assets"
              env:
                  DEPLOY_I18N: 'no'

            # Build upsellAds domain without packages
            - name: Build Upsell Ads
              run: yarn build:upsellAds

            # Deploy the built assets to ES tester plugin assets
            - name: Deploy to Upsell Editor
              run: source tools/deploy.sh "eventsmart.com-website" "dev" "plugins/ee-saas-notification/assets"
              env:
                  DEPLOY_I18N: 'no'
