name: Pull Request checks

on: [pull_request]

env:
    PLAYWRIGHT_BROWSERS_PATH: 0 # See https://playwright.dev/docs/ci/#caching-browsers

jobs:
    # JOB to check if the files in a path have changed
    what-is-hit:
        runs-on: ubuntu-latest
        outputs:
            js: ${{ steps.filter.outputs.js }}
        steps:
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                  base: ${{ github.ref }}
                  filters: |
                      js:
                        - 'domains/**'
                        - 'packages/**'
                        - 'yarn.lock'

    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                task: [lint, build, test]
        name: ${{ matrix.task }}
        needs: what-is-hit
        steps:
            - name: Checkout the commit
              uses: actions/checkout@v2
              with:
                  # To make sure all history is fetched for jest --changedSince to work as expected
                  fetch-depth: ${{ ( matrix.task != 'test' && 1 ) || 0 }} # 0 for test, 1 otherwise

            # TODO replace this when setup-node action supports LTS alias
            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              # install deps only if lockfile has changed
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Set test CLI args
              if: ${{ matrix.task == 'test' }}
              run: echo "CLI_ARGS=--changedSince ${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

            - name: Run ${{ matrix.task }}
              # Run the task only if JS is affected
              if: ${{ needs.what-is-hit.outputs.js == 'true' }}
              run: yarn ${{ matrix.task }}:ci ${{ env.CLI_ARGS }}

            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              if: ${{ matrix.task == 'build' && needs.what-is-hit.outputs.js == 'true' }}
              with:
                  name: build
                  path: build/

    e2e:
        env:
            # If you want to run e2e in parallel to build, just set this to false and comment out needs: and if:
            run_after_build: 'true'
        name: E2E Tests
        needs: [build, what-is-hit]
        runs-on: ubuntu-latest
        # Run the job only if JS is affected
        if: ${{ needs.what-is-hit.outputs.js == 'true' }}
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node
              uses: dcodeIO/setup-node-nvm@master
              with:
                  node-version: lts/*

            - name: Cache dependencies
              id: cache-deps
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              if: steps.cache-deps.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

            - name: Download build artifact
              # Download artifact only if running after build job
              if: ${{ fromJson(env.run_after_build) }}
              uses: actions/download-artifact@v2
              with:
                  name: build
                  path: build/

            # Leave this here just in case "needs" field is removed, then it can be enabled
            - name: Build barista assets
              # Build assets only if running in parallel to build/test
              if: ${{ ! fromJson(env.run_after_build) }}
              run: yarn && yarn build

            - name: Install WordPress
              run: yarn wp-env start

            - name: Setup Playwright
              uses: microsoft/playwright-github-action@v1

            - name: Run E2E tests
              run: yarn test:e2e

            - name: Archive debug artifacts (screenshots, HTML snapshots)
              uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: playwright-artifacts
                  path: artifacts
